[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
ANTHROPIC_AUTH_TOKEN = "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"
ANTHROPIC_BASE_URL = "https://openrouter.ai/api"
ANTHROPIC_DEFAULT_HAIKU_MODEL = "nvidia/nemotron-3-ultra-550b-a55b:free"
ANTHROPIC_DEFAULT_OPUS_MODEL = "openrouter/free"
ANTHROPIC_DEFAULT_SONNET_MODEL = "openai/gpt-oss-120b:free"
